### PR TITLE
Include version number in extracted path

### LINKED ISSUE #26: Track currently used version of driver
We aren't tracking the currently used version of the driver anywhere which means that we don't overwrite the binary of a new one has been downloaded.  

Solution is probably going to be store a version number, or a hash of the extracted file/files somewhere so we know that we need to update.

### PR DESCRIPTION
**Pull request by Artur-**
Fixes #26

### CODE REVIEW

**Comment by Artur-** [comment]
Friendly ping. 

This PR would help to make sure you are always using the version you think you are using.

**Comment by mpkorstanje** [comment]
@Ardesco I think this is worth adding.

**Comment by Artur-** [comment]
Alright. I don't see why it is a problem though that old versions would be kept around unless you go and delete them manually. My `~/.m2` folder is full of old versions of libs I do not actively use. If it becomes a problem, I go and delete them and they are redownloaded if still needed by some build. Maybe I am using the plugin in a different way than you but I don't see why it should even try to remove old versions.

**Comment by Ardesco** [comment]
Assuming we don't care about cleanup you still have the rest of the problems noted above.  Remember there is no guarantee that the version number used actually relates to the version of the binary you are downloading.

We could save the binaries to a folder that matches the hash of the file, that would guarantee that the binary in the folder is the expected one, but a file hash isn't very meaningful.

I find that giving people wrong information is worse than not providing information at all, this PR will provide people with information that can quite easily be wrong.  

You will know what version of a driver binary is used when you run your tests anyway, thanks to output like this:

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.lazerycode.selenium.tests.GoogleExampleIT
 
Local Operating System: MAC OS X
Local Architecture: x86_64
Selected Browser: firefox
Connecting to Selenium Grid: false
 
1523714359544	geckodriver	INFO	geckodriver 0.20.0
1523714359550	geckodriver	INFO	Listening on 127.0.0.1:34501
```

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.lazerycode.selenium.tests.GoogleExampleIT
 
Local Operating System: MAC OS X
Local Architecture: x86_64
Selected Browser: chrome
Connecting to Selenium Grid: false
 
Starting ChromeDriver 2.37.544337 (8c0344a12e552148c185f7d5117db1f28d6c9e85) on port 1136
Only local connections are allowed.
Apr 14, 2018 3:00:16 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
```

I agree that your solution would work in a happy path scenario.  However I think it would cause more confusion in the long run and I would expect to see bugs raised along the lines of:

> Chromedriver version 2.35 was downloaded but it's using Chromedriver version 2.42 in my tests!!!

If you can convince me otherwise and provide code to mitigate the listed problems I'll happily look at it again, we are in danger of adding complex code into the codebase that provides very little utility though.

**Comment by enver-haase** [comment]
Whatever goes in the extracted path, I would like to be able to propagate this to Java/Selenium when it is executing. Currently I am setting
<webdriver.chrome.driver>/path/to/binary</webdriver.chrome.driver> manually in <systemPropertyVariables> in the failsafe-plugin configuration.

And already this is hard to make OS independent, as the Java code needs to know about the path choices of this plugin here. Better to propagate it somehow, e.g. use
${os.name} and such properties instead of "linux" / "osx" .

**Comment by Ardesco** [comment]
Discussion for the extracted path is in comments for #89

**Pull request closed without merging**
